# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2009 Freescale Semiconductor, Inc.

#obj-y += cache.o
#obj-y += image_data.o
#obj-y += timer.c
obj-y += cpu.o
#obj-y += lowlevel_init.o
